// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qobdsqwzfnbxeyvahhxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvYmRzcXd6Zm5ieGV5dmFoaHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzQ4NTAsImV4cCI6MjA3MTM1MDg1MH0.WuOanGgmEN2DWVjcC3ZV6z7r_No9PW88DEd7P-uQp04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});